#! /bin/sh

sxhkd &

bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

# bspc monitor -d I II III IV V VI VIII IX

bspc monitor eDP-1 -d IV V VI VII VIII IX X
bspc monitor DP-1 -d I II III

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Custom scripts

## Layout scripts
# ~/.screenlayout/vertical-position.sh &
~/.screenlayout/screen-position.sh &
# ~/.screenlayout/screen-position-home.sh &

~/.config/polybar/launch.sh &
~/.fehbg &
nm-applet &
killall -q compton; compton --config ~/.config/compton.conf &
xsetroot -cursor_name left_ptr &
redshift &
